const ACCESS_TOKEN_STORAGE_NAME = 'access_token';
const AUTH_STATE_KEY = 'auth_state';
const PREVIOUS_ROUTE_STORAGE_NAME = 'previous_route';
const RECENTLY_CREATED_ACCOUNT_STORAGE_NAME = 'account_created';
const REFRESH_TOKEN_STORAGE_NAME = 'refresh_token';
const UNAUTHENTICATED_USER_ERROR_MESSAGE = 'User is not authenticated';

export const AUTH_CONSTANTS = {
  ACCESS_TOKEN_STORAGE_NAME,
  AUTH_STATE_KEY,
  PREVIOUS_ROUTE_STORAGE_NAME,
  RECENTLY_CREATED_ACCOUNT_STORAGE_NAME,
  REFRESH_TOKEN_STORAGE_NAME,
  UNAUTHENTICATED_USER_ERROR_MESSAGE,
};
